name: URLAnalyser
channels:
  - conda-forge
  - defaults
dependencies:
  - cloudpickle
  - h5py
  - joblib
  - numpy
  - ca-certificates
  - keras-applications
  - hdf5
  - pandoc
  - theano
  - pygpu
  - tensorflow-estimator
  - jsonschema
  - scipy
  - python-dateutil
  - ipython
  - keras==2.3.1
  - tensorflow-base==1.14.0
  - python==3.6.15
  - scikit-learn
  - pip
  - pickleshare
  - tensorflow==1.14.0
  - keras-preprocessing
  - openssl
  - setuptools
  - colorama
  - wheel
  - pandas
  - pytest
  - pytest-cov
  - requests
  - flake8
  - autopep8
  - mock
  - pip:
    - python-whois
    - pythonping
    - talos
prefix: C:\Users\edgor\anaconda3\envs\URLAnalyser
