# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint and Test Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CACHE_NUMBER: 0

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout URL-Analyser
      uses: actions/checkout@v3
    - name: Setup Anaconda
      uses: goanpeca/setup-miniconda@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        auto-update-conda: true
        auto-activate-base: false
        miniconda-version: 'latest'
        python-version: "3.6.15"
        environment-file: environment.yml
        activate-environment: URLAnalyser
      
    - name: Activate Environment
      shell: pwsh
      run: |
        conda activate URLAnalyser
    - name: Lint with flake8
      shell: pwsh
      run: |
        python -m flake8 . --max-line-length=120 
    - name: Test with pytest
      shell: pwsh
      run: |
        python -m pytest URLAnalyser/tests/ --disable-pytest-warnings --cov=URLAnalyser -vs
